# Generated by Django 5.2.4 on 2025-07-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0003_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
