# Generated by Django 5.2.4 on 2025-07-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0004_review_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='actor',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='director',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='genre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='running_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
