# Generated by Django 5.2.4 on 2025-07-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0005_review_actor_review_director_review_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('action', '액션'), ('comedy', '코미디'), ('drama', '드라마'), ('thriller', '스릴러'), ('romance', '로맨스')], max_length=20),
        ),
    ]
