# Generated by Django 5.2.4 on 2025-07-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtool',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devtool',
            name='kind',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
